(()=>{
const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
const isCasePage=!!q('article.case') && /case-studies/i.test(document.title);

function upgradeHero(){
  const lead=q('.hero .lead'); if(!lead||q('.dg-result-chips')) return;
  lead.insertAdjacentHTML('afterend','<div class="dg-result-chips"><span class="dg-result-chip"><b>Mehr</b> qualifizierte Anfragen</span><span class="dg-result-chip"><b>Stärkere</b> Bewerbungen</span><span class="dg-result-chip"><b>Weniger</b> Preisdiskussionen</span></div>');
}

function impactSection(){
  if(q('.dg-impact-section')||!q('#cases')) return;
  const section=document.createElement('section');section.className='dg-impact-section';section.id='wirkung';
  section.innerHTML=`<div class="container"><div class="dg-impact-head reveal"><div><span class="eyebrow">Was fehlendes Vertrauen wirklich auslöst</span><h2 class="serif">Gute Arbeit allein <span class="gold">verkauft sich online nicht.</span></h2></div><p>Wenn Qualität nicht sichtbar wird, entscheiden Menschen nicht gegen Ihre Leistung – sondern gegen die Unsicherheit.</p></div><div class="dg-impact-grid">
  ${impact('01','Besucher vergleichen nur den Preis','Ist der Unterschied zu anderen Anbietern nicht erkennbar, bleibt nur der Preis als Entscheidungskriterium.','Margen, Abschlussquote und Wertwahrnehmung.','Positionierung, Beweise und sichtbare Qualität.')}
  ${impact('02','Empfehlungen werden online nicht bestätigt','Fast jede Empfehlung führt zuerst zu Google und Website. Bestätigt der Auftritt das gute Gefühl nicht, entsteht Zweifel.','Warme Leads, die eigentlich fast überzeugt waren.','Ein konsistenter erster Eindruck über alle Kanäle.')}
  ${impact('03','Werbung erzeugt Klicks, aber keine Anfragen','Ads kaufen Aufmerksamkeit. Die Website muss daraus Vertrauen und eine klare Entscheidung machen.','Werbebudget, Zeit und planbare Kundengewinnung.','Vertrauensstarke Landingpages und klare nächste Schritte.')}
  ${impact('04','Gute Mitarbeiter erkennen den Arbeitgeberwert nicht','Menschen prüfen Führung, Kultur, Sicherheit und Zukunft – nicht nur die Stellenbeschreibung.','Passende Bewerbungen und Geschwindigkeit im Recruiting.','Menschen, Werte und Arbeitsrealität glaubwürdig sichtbar machen.')}
  </div><div class="dg-outcomes reveal"><div class="dg-outcome"><b>Mehr qualifizierte Anfragen</b><span>weil der Wert vor dem Gespräch verstanden wird</span></div><div class="dg-outcome"><b>Stärkere Bewerbungen</b><span>weil Kultur und Sicherheit sichtbar werden</span></div><div class="dg-outcome"><b>Effizientere Werbung</b><span>weil Klicks auf einen überzeugenden Auftritt treffen</span></div><div class="dg-outcome"><b>Schnellere Entscheidungen</b><span>weil weniger offene Zweifel bleiben</span></div></div>${roi()}</div>`;
  q('#cases').insertAdjacentElement('beforebegin',section);bindRoi();observe(section);
}
function impact(n,title,text,cost,solution){return `<article class="dg-impact-card reveal"><div class="dg-impact-title"><span class="dg-impact-number">${n}</span><h3>${title}</h3></div><p>${text}</p><div class="dg-impact-bottom"><div class="dg-cost"><b>Das kostet</b><span>${cost}</span></div><div class="dg-solution"><b>Das lösen wir</b><span>${solution}</span></div></div></article>`}
function roi(){return `<div class="dg-roi reveal"><div class="dg-roi-grid"><div><span class="eyebrow">Einfache Beispielrechnung</span><h2 class="serif">Was kann nur <span class="gold">1 % mehr Vertrauen</span> bewirken?</h2><p class="muted">Schon ein kleiner zusätzlicher Anteil an Anfragen kann die wirtschaftliche Wirkung des gesamten Online-Auftritts verändern.</p><div class="dg-roi-fields"><div class="dg-roi-field"><label>Website-Besucher pro Monat</label><input id="dgVisitors" type="number" min="0" value="500"></div><div class="dg-roi-field"><label>Ø Auftragswert in €</label><input id="dgValue" type="number" min="0" value="5000"></div><div class="dg-roi-field"><label>Abschlussquote aus Anfragen (%)</label><input id="dgClose" type="number" min="0" max="100" value="20"></div><div class="dg-roi-field"><label>Zusätzliche Anfragequote (%)</label><input id="dgLift" type="number" min="0.1" max="10" step="0.1" value="1"></div></div></div><div class="dg-roi-output"><small>Mögliches zusätzliches Umsatzpotenzial pro Jahr</small><strong id="dgRevenue">60.000 €</strong><p>Wenn nur ein kleiner zusätzlicher Anteil der Besucher genug Vertrauen fasst, um anzufragen.</p><div class="dg-roi-mini"><div><b id="dgLeads">5</b><span>zusätzliche Anfragen / Monat</span></div><div><b id="dgClients">1,0</b><span>zusätzliche Kunden / Monat</span></div></div><div class="dg-roi-note">Beispielrechnung zur Einordnung, keine Ergebnisgarantie.</div></div></div></div>`}
function bindRoi(){const ids=['dgVisitors','dgValue','dgClose','dgLift'];if(!q('#dgVisitors'))return;const euro=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);const calc=()=>{const v=Math.max(0,+q('#dgVisitors').value||0),value=Math.max(0,+q('#dgValue').value||0),close=Math.max(0,+q('#dgClose').value||0)/100,lift=Math.max(0,+q('#dgLift').value||0)/100;const leads=v*lift,clients=leads*close;q('#dgLeads').textContent=leads.toLocaleString('de-DE',{maximumFractionDigits:1});q('#dgClients').textContent=clients.toLocaleString('de-DE',{maximumFractionDigits:1});q('#dgRevenue').textContent=euro(clients*value*12)};ids.forEach(id=>q('#'+id).addEventListener('input',calc));calc()}

function upgradePillars(){const data=[['schwacher erster Eindruck','Profil, Bewertungen und Beweise','mehr qualifizierte Besucher'],['Wert wird nicht verstanden','klare Botschaft und Conversion-Struktur','mehr passende Anfragen'],['Menschen und Kultur bleiben unsichtbar','Gesichter, Haltung und Expertise','wärmere Kunden und Bewerber']];qa('.pillar').slice(0,3).forEach((p,i)=>{if(q('.dg-flow',p))return;const target=q('p',p);if(!target)return;target.insertAdjacentHTML('afterend',`<div class="dg-flow"><div><b>Problem</b><span>${data[i][0]}</span></div><div><b>Lösung</b><span>${data[i][1]}</span></div><div><b>Ergebnis</b><span>${data[i][2]}</span></div></div>`)})}

const cases=[
 {cls:'dg-relationship',name:'Strong Relationship',sector:'Paarberatung & Beziehungsbegleitung',url:'strongrelationship.de',img:'https://image.thum.io/get/width/1400/crop/760/noanimate/https://strongrelationship.de',summary:'Eine sensible Leistung musste sich sicher, warm und professionell anfühlen – ohne Druck, Schuldzuweisung oder typische Coaching-Phrasen.',problem:'Hohe emotionale Hürde vor der ersten Kontaktaufnahme.',solution:'Ruhige Positionierung, persönliches Vertrauen und ein niedrigschwelliger Beziehungscheck.',result:'Besucher fühlen sich verstanden und erhalten einen sicheren ersten Schritt statt einer harten Verkaufsaufforderung.',floatA:'Unsicherheit vor dem Erstkontakt',floatB:'Sicherheit, Orientierung, niedrigere Hürde',anchor:'strong-relationship'},
 {cls:'dg-libi',name:'Libi Elektronik',sector:'Elektronik, IT & Energie',url:'libielektronik.de',img:'https://image.thum.io/get/width/1400/crop/760/noanimate/https://libielektronik.de',summary:'Ein Unternehmen mit jahrzehntelanger Erfahrung und vielen Leistungen wirkte online nicht so klar und modern wie in der Realität.',problem:'Breites Leistungsspektrum, technische Komplexität und zu wenig sichtbare regionale Stärke.',solution:'Leistungsarchitektur, echte Projekte, Google-Signale und klare Kontaktwege.',result:'Privat- und Gewerbekunden verstehen schneller, was angeboten wird und warum der regionale Anbieter Sicherheit bietet.',floatA:'Technik war schwer einzuordnen',floatB:'lokales Vertrauen und klare Leistungen',anchor:'libi-elektronik'},
 {cls:'dg-neuromind',name:'NeuroMind Breathwork',sector:'Ausbildung & Mentoring',url:'neuromind-breathwork.de',img:'https://image.thum.io/get/width/1400/crop/760/noanimate/https://neuromind-breathwork.de',summary:'Eine tiefgehende Premium-Ausbildung musste klar von oberflächlichen Technik-Angeboten abgegrenzt werden.',problem:'Erklärungsbedürftiges Angebot und eine anspruchsvolle, skeptische Zielgruppe.',solution:'Haltungsbasierte Positionierung, fachliche Tiefe, Video und klarer Ausbildungsweg.',result:'Die richtigen Menschen erkennen schneller, dass es um Substanz, Sicherheit und professionelle Begleitung geht.',floatA:'zu wenig Differenzierung',floatB:'Tiefe, Sicherheit, Premium-Wahrnehmung',anchor:'neuromind'},
 {cls:'dg-koerperkult',name:'Körperkult',sector:'Beauty E-Commerce & Markenauftritt',url:'koerperkult-shop.de',img:'https://image.thum.io/get/width/1400/crop/760/noanimate/https://koerperkult-shop.de',summary:'Premium-Produkte mussten sich hochwertig, vertrauenswürdig und zugleich leicht kaufbar anfühlen.',problem:'Qualität war vorhanden, wurde im Shop aber nicht konsequent wahrgenommen.',solution:'Ruhige Premium-Ästhetik, klare Kategorien, Beratung und sichere Kauf-Signale.',result:'Kundinnen können Qualität schneller einordnen und werden intuitiv von der Entdeckung bis zum Kauf geführt.',floatA:'zu wenig Wertwahrnehmung',floatB:'Premium-Wirkung und Kaufklarheit',anchor:'koerperkult'}
];
function upgradeCases(){const section=q('#cases');if(!section||section.classList.contains('dg-upgraded'))return;section.classList.add('dg-upgraded');section.innerHTML=`<div class="dg-case-intro reveal"><span class="eyebrow">Keine großen Versprechen. Sichtbare Arbeit.</span><h2 class="serif">Case Studies als <span class="gold">echter Vertrauensbeweis.</span></h2><p class="lead">Nicht nur ansehen, was gebaut wurde. Verstehen, welches Problem gelöst wurde und wie daraus mehr Klarheit, Wertwahrnehmung und Entscheidungssicherheit entsteht.</p></div>${cases.map((c,i)=>showcase(c,i)).join('')}<div class="container dg-case-more reveal"><p>Plus sechs weitere Markenwelten aus E-Commerce, Events, Personal Branding und Führungskräfteentwicklung.</p><a class="btn btn-primary" href="case-studies.html">Alle 10 Case Studies erleben →</a></div>`;observe(section)}
function showcase(c,i){return `<article class="dg-showcase ${c.cls}"><div class="dg-showcase-shell"><div class="dg-showcase-copy reveal"><div class="dg-case-number">Case ${String(i+1).padStart(2,'0')}</div><h3>${c.name}</h3><div class="dg-case-sector">${c.sector}</div><p class="dg-case-summary">${c.summary}</p><div class="dg-case-logic"><div><b>Ausgangslage</b><span>${c.problem}</span></div><div><b>Umsetzung</b><span>${c.solution}</span></div><div class="dg-result"><b>Wirkung</b><span>${c.result}</span></div></div><a class="btn" href="case-studies.html#${c.anchor}">Vollständige Case Study →</a></div><div class="dg-case-visual reveal"><div class="dg-device"><div class="dg-browser"><i></i><i></i><i></i><span>${c.url}</span></div><div class="dg-screen"><img src="${c.img}" alt="Case Study ${c.name}" loading="lazy"></div></div><div class="dg-case-float dg-float-a"><b>Problem gelöst</b>${c.floatA}</div><div class="dg-case-float dg-float-b"><b>Ergebnis</b>${c.floatB}</div></div></div></article>`}

function upgradeProcess(){const labels=['Ergebnis: klare Vertrauenslücken','Ergebnis: weniger Vergleichbarkeit','Ergebnis: mehr Entscheidungssicherheit','Ergebnis: bessere Wirkung aus jedem Besucher'];qa('.step').slice(0,4).forEach((s,i)=>{if(q('.dg-process-result',s))return;(q('div:last-child',s)||s).insertAdjacentHTML('beforeend',`<span class="dg-process-result">${labels[i]}</span>`)})}

const caseOutcomes={
 'strong-relationship':['Sicherer Erstkontakt','Aus einer emotional hohen Hürde wird ein ruhiger, verständlicher erster Schritt. Das stärkt passende Kontaktanfragen statt Druck.'],
 'asmr-time':['Stärkeres Einkaufserlebnis','Markencharakter, Orientierung und Kaufvertrauen arbeiten zusammen – damit Produkte leichter gefunden und sicherer gewählt werden.'],
 'dj-walli':['Weniger Preisvergleich','Erfahrung, Persönlichkeit und echte Stimmen machen den Unterschied sichtbar. Die Anfrage dreht sich stärker um den passenden DJ als nur um den Preis.'],
 'jj-media':['Passendere Projektanfragen','Die Leistung wird schneller verstanden, die Person als Expertin erkennbar und die Zusammenarbeit klarer vorqualifiziert.'],
 'defi-intelligence':['Struktur statt Spekulation','Ein komplexes Thema wird als nachvollziehbarer Premium-Prozess wahrgenommen. Das reduziert Skepsis und verbessert die Gesprächsqualität.'],
 'kitan-design':['Klarere Kaufentscheidung','Spannung, Community und Trust-Signale führen gemeinsam zur Handlung, ohne dass das Shop-Erlebnis chaotisch wirkt.'],
 'koerperkult':['Höhere Wertwahrnehmung','Produktqualität, Beratung und sichere Abläufe werden sichtbar. Der Shop verkauft nicht nur Produkte, sondern Kompetenz und Vertrauen.'],
 'libi-elektronik':['Mehr Orientierung und lokale Sicherheit','Mehrere technische Leistungen werden einfach einordenbar. Echte Projekte und regionale Nähe erleichtern den nächsten Kontakt.'],
 'fuehrungskraefte':['Wert schneller verstanden','Die Zielgruppe erkennt sofort das eigene Problem, die konkrete Entwicklung und warum das Angebot relevant ist.'],
 'neuromind':['Klare Premium-Differenzierung','Tiefe, Haltung und fachliche Sicherheit grenzen die Ausbildung von oberflächlichen Angeboten ab und ziehen passendere Interessenten an.']
};
function upgradeCasePage(){document.body.classList.add('dg-case-page');qa('article.case').forEach(a=>{const data=caseOutcomes[a.id],focus=q('.focus',a);if(!data||!focus||q('.case-outcome-dg',a))return;focus.insertAdjacentHTML('afterend',`<div class="case-outcome-dg"><small>Klares Ergebnis</small><b>${data[0]}</b><span>${data[1]}</span></div>`)});const principle=q('.principle');if(principle&&!q('.dg-result-map'))principle.insertAdjacentHTML('beforebegin',`<section class="dg-result-map"><div class="wrap dg-result-map-grid"><div class="reveal"><span class="kicker">Was Vertrauen wirtschaftlich verändert</span><h2>Schönes Design ist nicht das Ergebnis. <em>Eine leichtere Entscheidung ist es.</em></h2><p>Jede Case Study löst ein anderes Problem. Die Logik bleibt gleich: weniger Zweifel, klarerer Wert und ein einfacher nächster Schritt.</p></div><div class="dg-result-map-cards"><article class="dg-result-map-card reveal"><b>Mehr qualifizierte Anfragen</b><span>Der Wert ist vor dem Gespräch klarer und Erwartungen passen besser zusammen.</span></article><article class="dg-result-map-card reveal"><b>Weniger Preisfokus</b><span>Unterschiede und Beweise machen den Preis zum Teil der Entscheidung – nicht zur einzigen Entscheidung.</span></article><article class="dg-result-map-card reveal"><b>Effizientere Werbung</b><span>Klicks treffen auf einen Auftritt, der Aufmerksamkeit in Vertrauen und Handlung übersetzt.</span></article><article class="dg-result-map-card reveal"><b>Stärkere Bewerbungen</b><span>Menschen, Kultur und Zukunft werden erkennbar, bevor das erste Gespräch beginnt.</span></article></div></div></section>`);observe(document)}

function observe(root=document){const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');o.unobserve(e.target)}}),{threshold:.08});qa('.reveal:not(.visible)',root).forEach(el=>o.observe(el))}
if(isCasePage){upgradeCasePage()}else{upgradeHero();impactSection();upgradePillars();upgradeCases();upgradeProcess()}observe();
})();
