import type { NextRequest } from 'next/server'
import { NextResponse } from 'next/server'

const payloadPrefixes = ['/admin', '/api', '/graphql', '/_next']

export function proxy(request: NextRequest) {
  const pathname = request.nextUrl.pathname

  if (payloadPrefixes.some((prefix) => pathname === prefix || pathname.startsWith(`${prefix}/`))) {
    return NextResponse.next()
  }

  if (pathname === '/') {
    return NextResponse.rewrite(new URL('/index.html', request.url))
  }

  // Files generated by the existing website build remain directly accessible.
  if (/\.[a-zA-Z0-9]+$/.test(pathname)) {
    return NextResponse.next()
  }

  const cleanPath = pathname.endsWith('/') ? pathname.slice(0, -1) : pathname
  return NextResponse.rewrite(new URL(`${cleanPath}.html`, request.url))
}

export const config = {
  matcher: ['/((?!_next/static|_next/image|favicon.ico).*)'],
}
